# Generated by Django 4.2.23 on 2025-07-22 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
