# Generated by Django 4.2.23 on 2025-07-23 09:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_step_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.SmallIntegerField(choices=[('image', 'Image'), ('gif', 'GIF'), ('video', 'Video')])),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media')),
                ('order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='app.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
