# Generated by Django 4.2.23 on 2025-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemedia',
            name='media_type',
            field=models.SmallIntegerField(choices=[(1, 'Image'), (2, 'GIF'), (3, 'Video')]),
        ),
    ]
