# Generated by Django 4.2.23 on 2025-07-29 11:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reaction_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image'),
        ),
    ]
