# Generated by Django 4.2.23 on 2025-07-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ingredient_quantity_remove_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeingredient',
            table='app_recipe_ingredient',
        ),
    ]
