# Generated by Django 4.2.23 on 2025-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recipe_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emotion',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (2, 'Love'), (3, 'Haha'), (4, 'Wow'), (5, 'Delicious'), (6, 'Angry')], default=1),
        ),
    ]
