# Generated by Django 4.2.23 on 2025-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reaction_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.SmallIntegerField(choices=[(0, 'Khác'), (1, 'Loại món'), (2, 'Dịp'), (3, 'Nguyên liệu chính'), (4, 'Chế độ ăn'), (5, 'Cách chế biến'), (6, 'Vùng miền'), (7, 'Hương vị')], default=0),
        ),
    ]
