# Generated by Django 4.2.23 on 2025-07-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeingredient',
            table='app_recipe_ingredients',
        ),
    ]
