# Generated by Django 4.2.23 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tag_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.SmallIntegerField(choices=[(1, 'Spam'), (2, 'Không phù hợp'), (3, 'Sai sự thật'), (4, 'Khác')]),
        ),
    ]
