# Generated by Django 4.2.23 on 2025-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Creating'), (0, 'Draft'), (1, 'Pending'), (2, 'Active'), (3, 'Inactive'), (4, 'Delete'), (5, 'Locked')], db_index=True, default=-1),
        ),
    ]
