# Generated by Django 4.2.23 on 2025-08-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cover_image',
        ),
    ]
