# Generated by Django 4.2.23 on 2025-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_recipe_cooking_time_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
