# Generated by Django 4.2.23 on 2025-08-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_recipe_view_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('recipe', 'user')},
        ),
    ]
