# Generated by Django 4.2.23 on 2025-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_view_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
