# Generated by Django 4.2.23 on 2025-08-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_recipe_rating_count_recipe_rating_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ip_address')},
            },
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
