# Generated by Django 4.2.23 on 2025-08-16 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_recipeview_delete_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
