# Generated by Django 4.2.23 on 2025-08-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_recipeview_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='RecipeReview',
        ),
    ]
