# Generated by Django 4.2.23 on 2025-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_review_recipereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
