# Generated by Django 4.2.23 on 2025-08-17 14:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_tag_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
    ]
