# Generated by Django 4.2.23 on 2025-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tag_image_alter_tag_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tags/'),
        ),
    ]
