# Generated by Django 4.2.23 on 2025-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_recipe_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Chờ xử lý'), (2, 'Đã xem xét'), (3, 'Hợp lệ'), (4, 'Không hợp lệ'), (5, 'Đã giải quyết')], db_index=True, default=1),
        ),
    ]
