# Generated by Django 4.2.23 on 2025-08-21 03:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_report_is_resolved_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Thời gian nấu (phút)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='app.RecipeIngredient', to='app.ingredient', verbose_name='Nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt đánh giá'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng sao'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(null=True, verbose_name='Số người ăn'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Creating'), (0, 'Draft'), (1, 'Pending'), (2, 'Active'), (3, 'Inactive'), (4, 'Delete'), (5, 'Locked')], db_index=True, default=-1, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=100, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ảnh'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Bước'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='tên'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.SmallIntegerField(choices=[(0, 'Khác'), (1, 'Loại món'), (2, 'Dịp'), (3, 'Nguyên liệu chính'), (4, 'Chế độ ăn'), (5, 'Cách chế biến'), (6, 'Vùng miền'), (7, 'Hương vị')], default=0, verbose_name='Thể loại tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.SmallIntegerField(choices=[(1, 'System'), (2, 'Google'), (3, 'Facebook')], default=1, verbose_name='Kiểu đăng nhập'),
        ),
    ]
