# Generated by Django 4.2.23 on 2025-08-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_comment_content_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình luận', 'verbose_name_plural': 'Các bình luận'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Nguyên liệu', 'verbose_name_plural': 'Các nguyên liệu'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Công thức', 'verbose_name_plural': 'Các công thức'},
        ),
        migrations.AlterModelOptions(
            name='recipemedia',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Các media'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order'], 'verbose_name': 'Bước', 'verbose_name_plural': 'Các bước'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Các tag'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Đang tạo'), (0, 'Nháp'), (1, 'Đang chờ'), (2, 'Đang hoạt động'), (3, 'Không hoạt động'), (4, 'Bị xóa'), (5, 'Bị khóa')], db_index=True, default=-1, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingredient', verbose_name='Nguyên liệu'),
        ),
    ]
