# Generated by Django 4.2.23 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Đang hoạt động'), (2, 'Không hoạt động'), (3, 'Bị xóa'), (4, 'Bị khóa')], db_index=True, default=1, verbose_name='Trạng thái'),
        ),
    ]
