# Generated by Django 4.2.23 on 2025-08-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_notification_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeView',
        ),
    ]
