# Generated by Django 4.2.23 on 2025-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_recipeview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Nguyên liệu', 'verbose_name_plural': 'Các nguyên liệu'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Các tag'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='app.RecipeTag', to='app.tag', verbose_name='Tag'),
        ),
    ]
